// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pnpWebAPIBackEnd.Models;

namespace pnpWebAPIBackEnd.Migrations
{
    [DbContext(typeof(UsersContext))]
    [Migration("20190723145350_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("pnpWebAPIBackEnd.Models.Users", b =>
                {
                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AddressType")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CommsMethod")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DateofBirth")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HomeNumber")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Identification")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoginStatus")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Suburb");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserType")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("WorkNumber")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Email");

                    b.ToTable("UsersDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
